import type { Player } from '../types/football';

/**
 * Generated by scripts/import-fc27.ts.
 * Empty until an authorized/licensed FC27 export is imported.
 */
export const FC27_IMPORTED_PLAYERS: Player[] = [];
